ShapeScale nodekit example.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7909,7 +7909,7 @@ fi
 # **************************************************************************
 # All files configure must automatically generate.
 
-ac_config_files="$ac_config_files Makefile components/Makefile coin-competitions/Makefile coin-competitions/SIM-20020118/Makefile coin-competitions/SIM-20011116/Makefile coin-competitions/SIM-20011005/Makefile coin-competitions/SIM-20010914/Makefile coin-competitions/SIM-20010824/Makefile coin-competitions/SIM-20010803/Makefile eyecandy/Makefile actions/Makefile draggers/Makefile engines/Makefile manipulators/Makefile nodes/Makefile sensors/Makefile"
+ac_config_files="$ac_config_files Makefile components/Makefile coin-competitions/Makefile coin-competitions/SIM-20020118/Makefile coin-competitions/SIM-20011116/Makefile coin-competitions/SIM-20011005/Makefile coin-competitions/SIM-20010914/Makefile coin-competitions/SIM-20010824/Makefile coin-competitions/SIM-20010803/Makefile eyecandy/Makefile actions/Makefile draggers/Makefile engines/Makefile manipulators/Makefile nodes/Makefile sensors/Makefile nodekits/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -8245,9 +8245,10 @@ do
   "manipulators/Makefile" ) CONFIG_FILES="$CONFIG_FILES manipulators/Makefile" ;;
   "nodes/Makefile" ) CONFIG_FILES="$CONFIG_FILES nodes/Makefile" ;;
   "sensors/Makefile" ) CONFIG_FILES="$CONFIG_FILES sensors/Makefile" ;;
+  "nodekits/Makefile" ) CONFIG_FILES="$CONFIG_FILES nodekits/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:8250: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8251: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8516,7 +8517,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8519: creating $ac_file" >&5
+    { echo "$as_me:8520: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8534,7 +8535,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8537: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8538: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8547,7 +8548,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8550: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8551: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8608,7 +8609,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8611: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8612: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8619,7 +8620,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8622: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8623: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8632,7 +8633,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8635: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8636: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8749,7 +8750,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8752: $ac_file is unchanged" >&5
+      { echo "$as_me:8753: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
