Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -874,8 +874,9 @@ Optional Packages:
   --with-opengl=DIR       OpenGL/Mesa installation directory
   --with-pthread=DIR      pthread installation directory
   --with-glu=DIR          use the OpenGL utility library [default=yes]
-  --with-inventor         use another Open Inventor than Coin [default=no]
-  --with-inventor=PATH    specify where Open Inventor resides
+  --with-inventor         use another Open Inventor than Coin [default=no],
+                          with InventorXt
+  --with-inventor=PATH    specify where Open Inventor and InventorXt resides
   --with-motif=DIR        use the Motif library default=yes
   --with-soxt             build against the SoXt toolkit
   --with-soqt             build against the SoQt toolkit
@@ -7105,6 +7106,7 @@ if test x"$with_pthread" != xno; then
     sim_ac_pthread_cppflags="-I${with_pthread}/include"
     sim_ac_pthread_ldflags="-L${with_pthread}/lib"
   fi
+  sim_ac_pthread_cppflags="-D_REENTRANT ${sim_ac_pthread_cppflags}"
   sim_ac_pthread_libs="-lpthread"
 
   sim_ac_save_cppflags=$CPPFLAGS
@@ -8535,7 +8537,7 @@ echo "$as_me: error: cannot find required '$sim_ac_gui_configcmd' utility" >&2;}
 
 
 
-if $soguiconfig $alternate_option --have-feature sliderset; then
+if false; then
   HAVE_SLIDERSETS_TRUE=
   HAVE_SLIDERSETS_FALSE='#'
 else
@@ -8544,7 +8546,7 @@ else
 fi
 
 
-if $soguiconfig $alternate_option --have-feature materialeditor; then
+if false; then
   HAVE_MATERIALEDITOR_TRUE=
   HAVE_MATERIALEDITOR_FALSE='#'
 else
@@ -8553,7 +8555,7 @@ else
 fi
 
 
-if $soguiconfig $alternate_option --have-feature directionallighteditor; then
+if false; then
   HAVE_DIRECTIONALLIGHTEDITOR_TRUE=
   HAVE_DIRECTIONALLIGHTEDITOR_FALSE='#'
 else
@@ -8562,7 +8564,7 @@ else
 fi
 
 
-if $soguiconfig $alternate_option --have-feature materiallist; then
+if false; then
   HAVE_MATERIALLIST_TRUE=
   HAVE_MATERIALLIST_FALSE='#'
 else
@@ -8571,7 +8573,7 @@ else
 fi
 
 
-if $soguiconfig $alternate_option --have-feature printdialog; then
+if false; then
   HAVE_PRINTDIALOG_TRUE=
   HAVE_PRINTDIALOG_FALSE='#'
 else
@@ -8769,6 +8771,65 @@ if $sim_cv_have_oiv_somarkerset_node; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SOMARKERSET 1
+_ACEOF
+
+
+else
+  :
+fi
+
+
+
+echo "$as_me:$LINENO: checking if the Open Inventor SoImage node is available" >&5
+echo $ECHO_N "checking if the Open Inventor SoImage node is available... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_soimage_node+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <Inventor/nodes/SoImage.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+SoImage * p = new SoImage;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_have_oiv_soimage_node=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+sim_cv_have_oiv_soimage_node=false
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_have_oiv_soimage_node" >&5
+echo "${ECHO_T}$sim_cv_have_oiv_soimage_node" >&6
+
+if $sim_cv_have_oiv_soimage_node; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SOIMAGE 1
 _ACEOF
 
 
