Integrate new SIM Coin Prog Compo entries in build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7528,7 +7528,7 @@ fi
 # **************************************************************************
 # All files configure must automatically generate.
 
-ac_config_files="$ac_config_files Makefile components/Makefile coin-competitions/Makefile coin-competitions/SIM-20011005/Makefile coin-competitions/SIM-20010914/Makefile coin-competitions/SIM-20010824/Makefile coin-competitions/SIM-20010803/Makefile eyecandy/Makefile actions/Makefile draggers/Makefile engines/Makefile manipulators/Makefile nodes/Makefile sensors/Makefile"
+ac_config_files="$ac_config_files Makefile components/Makefile coin-competitions/Makefile coin-competitions/SIM-20011116/Makefile coin-competitions/SIM-20011005/Makefile coin-competitions/SIM-20010914/Makefile coin-competitions/SIM-20010824/Makefile coin-competitions/SIM-20010803/Makefile eyecandy/Makefile actions/Makefile draggers/Makefile engines/Makefile manipulators/Makefile nodes/Makefile sensors/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -7851,6 +7851,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "components/Makefile" ) CONFIG_FILES="$CONFIG_FILES components/Makefile" ;;
   "coin-competitions/Makefile" ) CONFIG_FILES="$CONFIG_FILES coin-competitions/Makefile" ;;
+  "coin-competitions/SIM-20011116/Makefile" ) CONFIG_FILES="$CONFIG_FILES coin-competitions/SIM-20011116/Makefile" ;;
   "coin-competitions/SIM-20011005/Makefile" ) CONFIG_FILES="$CONFIG_FILES coin-competitions/SIM-20011005/Makefile" ;;
   "coin-competitions/SIM-20010914/Makefile" ) CONFIG_FILES="$CONFIG_FILES coin-competitions/SIM-20010914/Makefile" ;;
   "coin-competitions/SIM-20010824/Makefile" ) CONFIG_FILES="$CONFIG_FILES coin-competitions/SIM-20010824/Makefile" ;;
@@ -7864,7 +7865,7 @@ do
   "sensors/Makefile" ) CONFIG_FILES="$CONFIG_FILES sensors/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:7867: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7868: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8133,7 +8134,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8136: creating $ac_file" >&5
+    { echo "$as_me:8137: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8151,7 +8152,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8154: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8155: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8164,7 +8165,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8167: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8168: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8225,7 +8226,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8228: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8229: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8236,7 +8237,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8239: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8240: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8249,7 +8250,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8252: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8253: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8366,7 +8367,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8369: $ac_file is unchanged" >&5
+      { echo "$as_me:8370: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
