bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8684,8 +8684,8 @@ esac
 
 
   if $sim_ac_have_qt_framework; then
-    sim_ac_qt_cppflags="-I$sim_ac_qt_framework_dir/QtCore.framework/Headers -I$sim_ac_qt_framework_dir/QtOpenGL.framework/Headers -I$sim_ac_qt_framework_dir/QtGui.framework/Headers -I$sim_ac_qt_framework_dir/Qt3Support.framework/Headers -F$sim_ac_qt_framework_dir"
-    sim_ac_qt_libs="-Wl,-F$sim_ac_qt_framework_dir -Wl,-framework,QtGui -Wl,-framework,QtOpenGL -Wl,-framework,QtCore -Wl,-framework,Qt3Support -Wl,-framework,QtXml -Wl,-framework,QtNetwork -Wl,-framework,QtSql"
+    sim_ac_qt_cppflags="-I$sim_ac_qt_framework_dir/QtCore.framework/Headers -I$sim_ac_qt_framework_dir/QtOpenGL.framework/Headers -I$sim_ac_qt_framework_dir/QtGui.framework/Headers -F$sim_ac_qt_framework_dir"
+    sim_ac_qt_libs="-Wl,-F$sim_ac_qt_framework_dir -Wl,-framework,QtGui -Wl,-framework,QtOpenGL -Wl,-framework,QtCore -Wl,-framework,QtXml -Wl,-framework,QtNetwork -Wl,-framework,QtSql"
   else
 
     sim_ac_qglobal_unresolved=true
@@ -9304,8 +9304,7 @@ echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
         ## Test all known possible combinations of linking against the
         ## Troll Tech Qt library:
         ##
-        ## * "-lQtGui -lQt3Support": Qt 4 on UNIX-like systems (with some
-        ##   obsoleted Qt 3 widgets)
+        ## * "-lQtGui": Qt 4 on UNIX-like systems
         ##
         ## * "-lqt-gl": links against the standard Debian version of the
         ##   Qt library with embedded QGL
@@ -9361,8 +9360,8 @@ echo $ECHO_N "checking for Qt library devkit... $ECHO_C" >&6
 
         for sim_ac_qt_cppflags_loop in "" "-DQT_DLL"; do
           for sim_ac_qt_libcheck in \
-              "-lQtGui${sim_ac_qt_suffix}${sim_ac_qt_major_version} -lQtCore${sim_ac_qt_suffix}${sim_ac_qt_major_version} -lQt3Support${sim_ac_qt_suffix}${sim_ac_qt_major_version}" \
-              "-lQtGui -lQt3Support" \
+              "-lQtGui${sim_ac_qt_suffix}${sim_ac_qt_major_version} -lQtCore${sim_ac_qt_suffix}${sim_ac_qt_major_version}" \
+              "-lQtGui" \
               "-lqt-gl" \
               "-lqt-mt" \
               "-lqt" \
@@ -14568,7 +14567,6 @@ fi
 # volumerendering/ directory.
 
 if test x"$sim_ac_gui_toolkit" = x"soqt"; then
-
   # Default to not look for SIM Voleon, as we'll get lots of warnings
   # from configure in the common case that it is _not_ available.
   sim_ac_simvoleon_desired=false
@@ -14820,6 +14818,101 @@ _ACEOF
       { { echo "$as_me:$LINENO: error: Detected old CVS checkout of SoGuiExamples, exiting. To fix, 'cd' to the SoGuiExamples/volumerendering/ directory, do a 'cvs co Cute' and re-run configure." >&5
 echo "$as_me: error: Detected old CVS checkout of SoGuiExamples, exiting. To fix, 'cd' to the SoGuiExamples/volumerendering/ directory, do a 'cvs co Cute' and re-run configure." >&2;}
    { (exit 1); exit 1; }; }
+    fi
+
+    # Check if Qt4 has been compiled with Qt3Support
+    if $sim_ac_using_qt_4; then
+      sim_ac_save_libs=$LIBS
+      LIBS="-lQt3Support $LIBS"
+      echo "$as_me:$LINENO: checking if Qt4 has Qt3Support enabled" >&5
+echo $ECHO_N "checking if Qt4 has Qt3Support enabled... $ECHO_C" >&6
+      ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Qt3Support/q3valuelist.h>
+int
+main ()
+{
+Q3ValueList<float> params;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_ac_qt3support_avail=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_ac_qt3support_avail=false
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+      ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      echo "$as_me:$LINENO: result: $sim_ac_qt3support_avail" >&5
+echo "${ECHO_T}$sim_ac_qt3support_avail" >&6
+
+      if $sim_ac_qt3support_avail; then
+
+if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|Qt3Support:found enabled in Qt4 and is being used"
+else
+  sim_ac_configuration_settings="Qt3Support:found enabled in Qt4 and is being used"
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_QT3SUPPORT_LIBRARY 1
+_ACEOF
+
+      else
+
+if test x"${sim_ac_configuration_settings+set}" = x"set"; then
+  sim_ac_configuration_settings="$sim_ac_configuration_settings|Qt3Support:is not being enabled in Qt4 used -- SIM Voleon examples not built"
+else
+  sim_ac_configuration_settings="Qt3Support:is not being enabled in Qt4 used -- SIM Voleon examples not built"
+fi
+
+        LIBS=$sim_ac_save_libs
+        { { echo "$as_me:$LINENO: error: Detected Qt4 usage but Qt3Support couldn't be found. This is currently required to run the SIMVoleon examples. To fix, you will need to enable Qt3Support in Qt4." >&5
+echo "$as_me: error: Detected Qt4 usage but Qt3Support couldn't be found. This is currently required to run the SIMVoleon examples. To fix, you will need to enable Qt3Support in Qt4." >&2;}
+   { (exit 1); exit 1; }; }
+      fi
     fi
 
 else
