Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9761,6 +9761,67 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for So${Gui}GLWidget::setAccumulationBuffer()" >&5
+echo $ECHO_N "checking for So${Gui}GLWidget::setAccumulationBuffer()... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Inventor/${Gui}/So${Gui}RenderArea.h>
+int
+main ()
+{
+
+   So${Gui}RenderArea * viewer = (So${Gui}RenderArea *) 0;
+   viewer->setAccumulationBuffer(FALSE);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer=false
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer" >&5
+echo "${ECHO_T}$sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer" >&6
+
+if $sim_cv_have_oiv_have_soguiglwidget_accumulationbuffer; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SOGUIGLWIDGET_ACCUMULATIONBUFFER 1
+_ACEOF
+
+
+else
+  :
+fi
+
+
+
+
 echo "$as_me:$LINENO: checking for SoIntersectionDetectionAction class" >&5
 echo $ECHO_N "checking for SoIntersectionDetectionAction class... $ECHO_C" >&6
 if test "${sim_cv_have_oiv_have_sointersectiondetectionaction+set}" = set; then
