Moved auxiliary scripts into cfg/. Added test for old CVS repository structure.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,7 +1,49 @@
 # **************************************************************************
 AC_INIT(actions/search.cpp.in)
+AC_CONFIG_AUX_DIR(cfg)
 
-# Locate C++ compiler and set C++ as the default compiler to run in tests.
+# **************************************************************************
+# Check the CVS repository setup
+
+sim_ac_cvs_syncproblem=false;
+
+sim_ac_macro_dir=${srcdir}/cfg/m4
+
+if test ! -d $sim_ac_macro_dir; then
+  if test "x${with_auto_cvs_update+set}" = "xset"; then
+    echo "Trying to honor the --with-auto-cvs-update option."
+    sim_ac_save_cwd="`pwd`"
+    cd ${srcdir}
+    if test -d cfg/m4 -o ! -f ./CVS/Entries; then
+      AC_MSG_ERROR([something failed horribly - can't do auto-cvs-update])
+    fi
+    test -d conf-macros && rm -rf conf-macros
+    cvs co SoGuiExampleMacros
+    cd ${sim_ac_save_cwd}
+    echo "Done.  Proceeding..."
+  fi
+fi
+
+if test ! -d $sim_ac_macro_dir; then
+  cat <<EOF
+
+  You appear to have an old setup of the SoGuiExamples source repository.
+  Parts of it have changed structurally, and you need to do the following
+  in the SoGuiExamples source directory:
+
+    $ rm -rf conf-macros
+    $ cvs co SoGuiExampleMacros
+
+  You can also run configure with the option --with-auto-cvs-update
+  to allow the configure script to try to take care of this.  This
+  option is a bit experimental - use at your own risk.
+EOF
+  sim_ac_cvs_syncproblem=true
+fi
+
+$sim_ac_cvs_syncproblem && echo "" && echo "Aborting..." && exit 1
+
+# **************************************************************************
 AC_PROG_CXX
 AC_LANG_CPLUSPLUS
 
@@ -20,8 +62,35 @@ AM_MAINTAINER_MODE
 # Initialize libtool
 AC_PROG_LIBTOOL
 
+SIM_AC_CHECK_LINKSTYLE
+
 # **************************************************************************
 # Search and set up necessary stuff to use the GUI library.
+
+sim_ac_gui_default=soxt
+# No Xt on Windows, so we default to Qt for the Windows platform
+test x"$sim_ac_linking_style" = xmswin && sim_ac_gui_default=soqt
+
+test x${with_qt+set} = xset && sim_ac_gui_default=soqt
+test x${with_xt+set} = xset && sim_ac_gui_default=soxt
+test x${with_gtk+set} = xset && sim_ac_gui_default=sogtk
+
+AC_ARG_WITH(
+  soxt,
+  AC_HELP_STRING([--with-soxt], [build against the SoXt toolkit]),
+  [sim_ac_gui_default=soxt])
+AC_ARG_WITH(
+  soqt,
+  AC_HELP_STRING([--with-soqt], [build against the SoQt toolkit]),
+  [sim_ac_gui_default=soqt])
+AC_ARG_WITH(
+  sowin,
+  AC_HELP_STRING([--with-sowin], [build against the SoWin toolkit]),
+  [sim_ac_gui_default=sowin])
+AC_ARG_WITH(
+  sogtk,
+  AC_HELP_STRING([--with-sogtk], [build against the SoGtk toolkit]),
+  [sim_ac_gui_default=sogtk])
 
 AC_ARG_WITH(
   toolkit,
@@ -31,13 +100,15 @@ AC_ARG_WITH(
   case $lwithval in
     xt  | soxt)    sim_ac_gui_toolkit=soxt  ;;
     qt  | soqt)    sim_ac_gui_toolkit=soqt  ;;
+    win | sowin)   sim_ac_gui_toolkit=sowin ;;
     gtk | sogtk)   sim_ac_gui_toolkit=sogtk ;;
     be  | sobe)    sim_ac_gui_toolkit=sobe  ;;
     iv  | oiv)     sim_ac_gui_toolkit=oiv   ;;
     *) AC_MSG_ERROR([invalid --with-toolkit value: "$withval"]) ;;
   esac],
-  [sim_ac_gui_toolkit=soxt])
+  [sim_ac_gui_toolkit=$sim_ac_gui_default])
 
+# **************************************************************************
 # Environment variables to configure the generic sourcefiles.
 
 sim_ac_path=$PATH
@@ -63,9 +134,9 @@ fi
 AC_SUBST(GUI)
 AC_SUBST(Gui)
 AC_SUBST(gui)
+AC_SUBST(EVENT)
 AC_SUBST(WIDGET)
 AC_SUBST(WINWIDGET)
-AC_SUBST(EVENT)
 AC_SUBST(COMPONENTHEADER)
 
 # Which examples to build. These env vars also taken from
