Test for So@Gui@Component::setFullScreen().

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6616,9 +6616,9 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-echo "$as_me:6619: checking for So${Gui}Viewer::setStereoViewing()" >&5
-echo $ECHO_N "checking for So${Gui}Viewer::setStereoViewing()... $ECHO_C" >&6
-if test "${sim_cv_have_oiv_have_viewer_stereo_viewing+set}" = set; then
+echo "$as_me:6619: checking for So${Gui}Component::setFullScreen()" >&5
+echo $ECHO_N "checking for So${Gui}Component::setFullScreen()... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_have_socomponent_setfullscreen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -6630,7 +6630,7 @@ main ()
 {
 
    So${Gui}ExaminerViewer * viewer = (So${Gui}ExaminerViewer *) 0;
-   viewer->setStereoViewing(FALSE);
+   viewer->setFullScreen(FALSE);
   ;
   return 0;
 }
@@ -6647,30 +6647,30 @@ if { (eval echo "$as_me:6639: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:6648: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_have_oiv_have_viewer_stereo_viewing=true
+  sim_cv_have_oiv_have_socomponent_setfullscreen=true
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-sim_cv_have_oiv_have_viewer_stereo_viewing=false
+sim_cv_have_oiv_have_socomponent_setfullscreen=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:6658: result: $sim_cv_have_oiv_have_viewer_stereo_viewing" >&5
-echo "${ECHO_T}$sim_cv_have_oiv_have_viewer_stereo_viewing" >&6
+echo "$as_me:6658: result: $sim_cv_have_oiv_have_socomponent_setfullscreen" >&5
+echo "${ECHO_T}$sim_cv_have_oiv_have_socomponent_setfullscreen" >&6
 
-if $sim_cv_have_oiv_have_viewer_stereo_viewing; then
+if $sim_cv_have_oiv_have_socomponent_setfullscreen; then
 
 cat >>confdefs.h <<\EOF
-#define HAVE_VIEWER_STEREO_VIEWING 1
+#define HAVE_SOCOMPONENT_SETFULLSCREEN 1
 EOF
 
 else
   :
 fi
 
-echo "$as_me:6671: checking for So${Gui}Viewer::setQuadBufferStereo()" >&5
-echo $ECHO_N "checking for So${Gui}Viewer::setQuadBufferStereo()... $ECHO_C" >&6
-if test "${sim_cv_have_oiv_have_viewer_quadbuffer_stereo+set}" = set; then
+echo "$as_me:6671: checking for So${Gui}Viewer::setStereoViewing()" >&5
+echo $ECHO_N "checking for So${Gui}Viewer::setStereoViewing()... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_have_viewer_stereo_viewing+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -6682,7 +6682,7 @@ main ()
 {
 
    So${Gui}ExaminerViewer * viewer = (So${Gui}ExaminerViewer *) 0;
-   viewer->setQuadBufferStereo(0);
+   viewer->setStereoViewing(FALSE);
   ;
   return 0;
 }
@@ -6699,6 +6699,58 @@ if { (eval echo "$as_me:6691: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:6700: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
+  sim_cv_have_oiv_have_viewer_stereo_viewing=true
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+sim_cv_have_oiv_have_viewer_stereo_viewing=false
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:6710: result: $sim_cv_have_oiv_have_viewer_stereo_viewing" >&5
+echo "${ECHO_T}$sim_cv_have_oiv_have_viewer_stereo_viewing" >&6
+
+if $sim_cv_have_oiv_have_viewer_stereo_viewing; then
+
+cat >>confdefs.h <<\EOF
+#define HAVE_VIEWER_STEREO_VIEWING 1
+EOF
+
+else
+  :
+fi
+
+echo "$as_me:6723: checking for So${Gui}Viewer::setQuadBufferStereo()" >&5
+echo $ECHO_N "checking for So${Gui}Viewer::setQuadBufferStereo()... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_have_viewer_quadbuffer_stereo+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line 6729 "configure"
+#include "confdefs.h"
+#include <Inventor/${Gui}/viewers/So${Gui}ExaminerViewer.h>
+int
+main ()
+{
+
+   So${Gui}ExaminerViewer * viewer = (So${Gui}ExaminerViewer *) 0;
+   viewer->setQuadBufferStereo(0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:6743: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:6746: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:6749: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:6752: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
   sim_cv_have_oiv_have_viewer_quadbuffer_stereo=true
 else
   echo "$as_me: failed program was:" >&5
@@ -6707,7 +6759,7 @@ sim_cv_have_oiv_have_viewer_quadbuffer_stereo=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:6710: result: $sim_cv_have_oiv_have_viewer_quadbuffer_stereo" >&5
+echo "$as_me:6762: result: $sim_cv_have_oiv_have_viewer_quadbuffer_stereo" >&5
 echo "${ECHO_T}$sim_cv_have_oiv_have_viewer_quadbuffer_stereo" >&6
 
 if $sim_cv_have_oiv_have_viewer_quadbuffer_stereo; then
@@ -6803,7 +6855,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6806: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6858: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -6979,7 +7031,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:6982: error: ambiguous option: $1
+    { { echo "$as_me:7034: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7013,12 +7065,12 @@ Try \`$0 --help' for more information." >&2;}
   'config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:7016: error: unrecognized option: $1
+  -*) { { echo "$as_me:7068: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:7021: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:7073: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7316,7 +7368,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7319: creating $ac_file" >&5
+    { echo "$as_me:7371: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7334,7 +7386,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7337: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7389: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7347,7 +7399,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7350: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7402: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7408,7 +7460,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7411: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7463: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7419,7 +7471,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7422: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7474: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7432,7 +7484,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7435: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7487: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7549,7 +7601,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7552: $ac_file is unchanged" >&5
+      { echo "$as_me:7604: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
